name: After release
on:
  release:
    types: [published]
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: create PR
        run: |
          gh pr create -B "develop" -H "develop" -t "Update develop with master after release ${GITHUB_REF}" -b "Use rebase to merge this PR!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}