name: After release
on:
  release:
    types: [published]
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: create PR
        run: |
          git config --global user.name "Github action"
          VERSION=$(echo $GITHUB_REF | grep -o -E "([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$")
          gh pr create -B "develop" -H "master" -t "Update develop with master after release ${VERSION}" -b "Use rebase to merge this PR!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}